/*************************************************************************
** Author:          Chelsea Hicks
** Date:            3/17/19
** Description:     The implementation file for the AlainBombard class defines
**                  the constructor for a AlainBombard character, setting
**                  the character's type, time needed for raft making, and 
**                  time limit for completing the task as well as 
**                  the functions for printing Dr. Bombards's characteristics,
**                  a function for decision making, and a function for 
**                  determining how much time he wastes munching on plankton.
*************************************************************************/

#include <iostream>
#include <iomanip>
#include <cstdlib>

#include "AlainBombard.hpp"

using std::cout;
using std::cin;
using std::endl;

/*Default Constructor - sets required time for raft making to 5, he has a lot of time to acquire items
for raft making since this isn't the Dr. Bombard's first rodeo. */
AlainBombard::AlainBombard()
{
    this->type = "Alain Bombard";
    this->raftMaking = 5;
    this->timeLimit = 115;
}

//Function prints the characteristics of a Dr. Bombard type
void AlainBombard::printChar()
{
    cout << "....................................................." << endl;
    cout << "Alain Bombard is famous for deliberately drifting " << endl;
    cout << "across the Atlantic for 65 days with no provisions--" << endl;
    cout << "subsisting on plankton, saltwater, and raw fish-- to " << endl;
    cout << "prove it was possible. Dr. Bombard arrived in Malnesia " << endl;
    cout << "on accident when his lifeboat went off course as he " << endl; 
    cout << "attempted to replicate his previous sefaring experiment." << endl;
    cout << endl;
    cout << "Dr. Bombard is a pure-blooded Frenchman and thus a " << endl;
    cout << "bold risk-taker. He embraces a challenge and is an " << endl;
    cout << "adept problem-solver. He has also acquired a taste " << endl;
    cout << "for plankton and salt-water." << endl;
    cout << "....................................................." << endl;
    cout << endl;
    cout << endl;
}

/*Function returns an random integer from a deterined range of 1-60 that represents a 
percent chance for Dr. Bombard to make a poor decision. This value will be compared to a set value 
in some randomEvents that occur in different spaces. */
int AlainBombard::decisionMaking()
{
    //Variable to hold the percent chance of Dr. Bombard making a poor decision
    int poorDecisionChance;

    poorDecisionChance = rand() % 60 + 1;

    return poorDecisionChance; 
}

//Function for Character to waste time eating plankton
int AlainBombard::wasteTime()
{
     int timeWasted;

    //Variable to hold the percent chance of Tina making a poor decision
    int poorDecisionChance = decisionMaking();

    /*If the random number generated by decisionMaking is greater than 50, then
    Alain makes a decision that doesn't help his survival. */
    if (poorDecisionChance > 50)
    {
        cout << "You've been craving some plankton and stored a flask of seawater in your pocket." << endl;
        cout << "You downed the flask and it made your feet swell. Time to take a breather." << endl;
        cout << endl;
        cout << "Time used: 3 hours" << endl;
        timeWasted = 3;
    }
    else
    {
        cout << "You're no fool, you know every second counts. There's no time to waste." << endl;
        timeWasted = 0;
    }
    
    return timeWasted; 
}

//Destructor
AlainBombard::~AlainBombard()
{

}