/*************************************************************************
** Author:          Chelsea Hicks
** Date:            3/17/19
** Description:     The implementation file for the FyreFestPhil class defines
**                  the constructor for a Phil character, setting
**                  the character's type, time needed for raft making, and 
**                  time limit for completing the task as well as 
**                  the functions for printing Phil's characteristics,
**                  a function for decision making, and a function for 
**                  determining how much time he wastes posting to social media.
*************************************************************************/

#include <iostream>
#include <iomanip>
#include <cstdlib>

#include "FyreFestPhil.hpp"

using std::cout;
using std::cin;
using std::endl;

/*Default Constructor - sets required time for raft making to 20, he has a decent chunk
of time to acquire materials so long as he doesn't get too distracted complaining on
social media about his disappointing experience in Malnesia. */
FyreFestPhil::FyreFestPhil()
{
    this->type = "Fyre Fest Phil";
    this->raftMaking = 20;
    this->timeLimit = 100;
}

//Function prints the characteristics of a Phil type
void FyreFestPhil::printChar()
{
    cout << "....................................................." << endl;
    cout << "Fyre Fest Phil is a survivor. After spending one " << endl;
    cout << "night in a FEMA tent in the Bahamas and subsisting on" << endl;
    cout << "George Clooney tequila and lettuce sandwiches," << endl; 
    cout << "Phil really feels like there's nothing he can't do." << endl;
    cout << endl;
    cout << "Phil purchased a package trip to Malnesia from a " << endl;
    cout << "flash ticket sale one of his buddies told him about. " << endl;
    cout << "All of his friends cancelled their trip at the last " << endl;
    cout << "minute. Phil is excited to meet other influencers" << endl;
    cout << "and let the sun shine on his new tattoo, the Chinese " << endl;
    cout << "character for courage." << endl;
    cout << "....................................................." << endl;
    cout << endl;
    cout << endl;

}

/*Function returns an random integer from a deterined range of 40-100 that represents a 
percent chance for Fyre Fest Phil to make a poor decision. This value will be compared 
to a set value in some randomEvents that occur in different spaces. */
int FyreFestPhil::decisionMaking()
{
    //Variable to hold the percent chance of Phil making a poor decision
    int poorDecisionChance;

    poorDecisionChance = rand() % 61 + 40;

    return poorDecisionChance; 
}

//Function for Character to waste time posting to social media about his less than stellar experience
int FyreFestPhil::wasteTime()
{
     int timeWasted;

    //Variable to hold the percent chance of Tina making a poor decision
    int poorDecisionChance = decisionMaking();

    /*If the random number generated by decisionMaking is greater than 45, then
    Phil makes a decision that doesn't help his survival. */
    if (poorDecisionChance > 45)
    {
        cout << "You record a video detailing your less than stellar experience in Malnesia." << endl;
        cout << "You're outraged by the situation and lack of wifi. You waste a lot of time trying " << endl;
        cout << "to find cell service before finally giving up." << endl;
        cout << endl;
        cout << "Time used: 4 hours" << endl;
        timeWasted = 4;
    }
    else
    {
        cout << "You're not wasting any time." << endl;
        cout << "You're is determined in this moment to get off the island!" << endl;
        timeWasted = 0;
    }
    
    return timeWasted; 
}

//Destructor
FyreFestPhil::~FyreFestPhil()
{

}