/*************************************************************************
** Author:          Chelsea Hicks
** Date:            3/17/19
** Description:     The implementation file for the MaryRobinson class defines
**                  the constructor for a MaryRobinson character, setting
**                  the character's type, time needed for raft making, and 
**                  time limit for completing the task as well as 
**                  the functions for printing President Robinson's characteristics,
**                  a function for decision making, and a function for 
**                  determining how much time she wastes trying to recover Wilson.
*************************************************************************/

#include <iostream>
#include <iomanip>
#include <cstdlib>

#include "MaryRobinson.hpp"

using std::cout;
using std::cin;
using std::endl;

/*Default Constructor - sets required time for raft making to 5, he has a lot of time to acquire items
for raft making since this isn't the Dr. Bombard's first rodeo. */
MaryRobinson::MaryRobinson()
{
    this->type = "Mary Robinson";
    this->raftMaking = 20;
    this->timeLimit = 100;
}
        
//Function prints the characteristics of a Mary type
void MaryRobinson::printChar()
{
    cout << "....................................................." << endl;
    cout << "Mary Robinson has dedicated her life to serving " << endl;
    cout << "others. She led the UN coordinated relocation plan " << endl;
    cout << "for the people of Malnesia, but was left behind " << endl;
    cout << "when the final boat of passengers departed." << endl;
    cout << endl;
    cout << "Mrs. Robinson is a competent and compassionate " << endl;
    cout << "leader and skilled problem-solver. She uses" << endl;
    cout << "her position to secure global justice for those " << endl;
    cout << "impacted by climate change, especially the poor and" << endl;
    cout << "disempowered." << endl;
    cout << "....................................................." << endl;
    cout << endl;
    cout << endl;

}

/*Function returns an random integer from a deterined range of 1-30 that represents a 
percent chance for Mary Robinson to make a poor decision. This value will be compared 
to a set value in some randomEvents that occur in different spaces. */
int MaryRobinson::decisionMaking()
{
    //Variable to hold the percent chance of President Robinson making a poor decision
    int poorDecisionChance;

    poorDecisionChance = rand() % 30 + 1;

    return poorDecisionChance;

}

//Function for Character to waste time saving Wilson
int MaryRobinson::wasteTime()
{
     int timeWasted;

    //Variable to hold the percent chance of Tina making a poor decision
    int poorDecisionChance = decisionMaking();

    /*If the random number generated by decisionMaking is greater than 25, then
    Mary makes a decision that doesn't help her survival. */
    if (poorDecisionChance > 25)
    {
        cout << "You've lost track of Wilson and even though he's...it's just a volleyball," << endl;
        cout << "he's the only friend you have on the island. You retrace your steps and " << endl;
        cout << "find Wilson after a few hours of searching." << endl;
        cout << endl;
        cout << "Time used: 3 hours" << endl;
        timeWasted = 3;
    }
    else
    {
        cout << "You're not one to waste time. You're focused on getting off of this island!" << endl;
        timeWasted = 0;
    }

    return timeWasted; 
}

//Destructor
MaryRobinson::~MaryRobinson()
{

}